### ISSUE TITLE
TODOs für Milestone 

### ISSUE THREAD

**Issue by srinortner** [srinortner/GameDesignSS2022#2]
- [x]  farbe on partikelsystem wenn collision mit farbiger plattform
- [x] Physics balancen
- [x] Häuser sichtbarer machen
- [x] Cubes spawnen von Partikelsystem
- [x] Balls force zur mitte
- [x] Gelbe Cubse bleiben auf plattform

**Comment by srinortner** [comment]
Eventuell noch skybox?

**Comment by Viktoria-1** [comment]
Vorschläge nach Feedback:
- [x] Begin Screen Text für basic Erklärung ODER Maus irgendwie besonders hervorheben, damit Leute sie besser wahrnehmen!
- [ ] Für Physics Sensitivity bar in Pause/Menü einbauen oder Hard/Medium/Easy mode ?
- [ ]  Sphere color über Timer ändern, wenn nicht berührt nach 10 Sekunden --> mehr auffällig

**Comment by srinortner** [comment]
Feedback Session 26.4.2022:

nach Priorität
- [x] - force nach vorne von hinten indem nur der erste "hit" zählt 
- [ ] - indikator in welche richtung die objekte springen werden
- [x] - Häuser lassen sich stapeln 
- [x] - kamerasteuerung mit linker maustaste
- [x] - musik ausschalten button

**Comment by srinortner** [comment]
- [x] Häuser lassen sich nur aufeinander und nicht ineinander stapeln
