### ISSUE TITLE
Feedback Milestone 1

### ISSUE THREAD

**Issue by srinortner** [srinortner/GameDesignSS2022#4]
- [x] Platforms are "magnetic" for cubes and spheres
- [x] Force addition not with sliders but with speed of the mouse or other mechanic
- [ ] maybe indicator where the cubes/spheres will jump
-> AC: max 2 jumps to place cube for developers

- [ ] Punishment for wrong colored cube on platform
