### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by srinortner** [srinortner/GameDesignSS2022#5]
- [ ] Kamerasteuerung mit Rand vom Bildschirm
- [ ] Spheres Force anpassen
- [ ] Rote Plattform einfacher machen
- [ ] Cubes die Häuser sind -> Rigidbody Static
